'use strict';
const $=id=>document.getElementById(id);let catalog=window.CARD_CATALOG||{cards:[],version:'empty'},state={items:{},custom:[],title:'我的卡片交換表',saleItems:{},saleTitle:'我的卡片販售表'},db,pageSize=40,previewGeneration=0,previewTimer;const imageCache=new Map(),bundledVersion=catalog.version;
function notify(t){$('status').textContent=t}function allCards(){return [...catalog.cards,...state.custom]}function flags(c){return state.items[c.uid]||{}}function code(c){return flags(c).code||c.code||c.catalogLabel||'自訂卡片'}
const ready=new Promise((resolve,reject)=>{const r=indexedDB.open('aipri-card-studio-v2',1);r.onupgradeneeded=()=>r.result.createObjectStore('data');r.onerror=()=>reject(r.error);r.onsuccess=()=>{db=r.result;const tx=db.transaction('data');const q=tx.objectStore('data').get('state'),cq=tx.objectStore('data').get('catalog');q.onsuccess=()=>{if(q.result)state={...state,...q.result};state.saleItems=state.saleItems||{}};cq.onsuccess=()=>{if(!window.IS_STANDALONE&&cq.result&&cq.result.version!==catalog.version&&cq.result.baseVersion===bundledVersion&&Array.isArray(cq.result.cards))catalog=cq.result};tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)}});
function write(key,value){return new Promise((resolve,reject)=>{if(!db)return reject(Error('本機資料庫不可用'));const tx=db.transaction('data','readwrite');tx.objectStore('data').put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
async function save(){try{await write('state',state)}catch(e){notify('儲存失敗，請立即備份清單：'+e.message)}}
function setField(c,k,v){state.items[c.uid]={...flags(c),[k]:v};save()}
function refreshSets(){const val=$('set').value;$('set').replaceChildren(new Option('所有彈數',''));[...new Set(allCards().map(c=>c.set).filter(Boolean))].sort((a,b)=>(a==='event'?7:a)-(b==='event'?7:b)).forEach(s=>$('set').add(new Option(s==='event'?'活動／商品卡':'第 '+s+' 彈',String(s))));$('set').value=val}
function textEl(tag,cls,text){const el=document.createElement(tag);el.className=cls;el.textContent=text;return el}
function render(){const cards=allCards(),q=$('search').value.trim().normalize('NFKC').toLowerCase(),set=$('set').value,rare=$('rarity').value,filter=$('filter').value,character=$('character').value;const selected=cards.filter(c=>{const f=flags(c);return (!character||c.character===character)&&(!set||String(c.set)===set)&&(!rare||String(c.rarity)===rare)&&(!q||(code(c)+' '+c.name+' '+(c.character||'')).normalize('NFKC').toLowerCase().includes(q))&&(filter==='all'||(filter==='sale'?saleFlags(c).selected:(filter==='selected'?(f.have||f.want):f[filter])))});sortCards(selected);$('cards').replaceChildren();$('empty').hidden=selected.length>0;$('more').hidden=selected.length<=pageSize;$('total').textContent=`圖庫 ${cards.length} 張 · 顯示 ${Math.min(pageSize,selected.length)} / ${selected.length}`;$('counts').textContent=`讓 ${cards.filter(c=>flags(c).have).length} 張　／　求 ${cards.filter(c=>flags(c).want).length} 張`;$('version').textContent=`圖庫版本 ${catalog.version} · 官方第 ${[...new Set(catalog.cards.map(c=>c.set).filter(s=>s!=='event'))].sort().join('、')} 彈`;
 for(const c of selected.slice(0,pageSize)){const f=flags(c),article=textEl('article','card',''),button=textEl('button','image-button',''),img=document.createElement('img'),tag=textEl('span','flip-tag',c.back?'↻ 看背面':'僅正面');img.src=c.front;img.alt=(c.name||code(c))+' 正面';img.loading='lazy';button.setAttribute('aria-label',c.name+'，點擊切換正反面');button.append(img,tag);let back=false;button.onclick=()=>{if(!c.back)return;back=!back;img.src=back?c.back:c.front;img.alt=c.name+(back?' 背面':' 正面');tag.textContent=back?'↻ 看正面':'↻ 看背面'};article.append(button,textEl('div','code',code(c)),textEl('div','card-name',c.name),textEl('div','card-meta',(c.character||'自訂')+(c.rarity?' · '+'★'.repeat(c.rarity):'')+(c.category?' · '+(c.category==='product'?'商品卡':'活動卡'):'')+(c.missingBackReason?' · 缺背面':'')));const note=document.createElement('input');note.value=f.note||'';note.placeholder='交換備註…';note.setAttribute('aria-label',code(c)+' 備註');note.oninput=()=>{setField(c,'note',note.value);schedulePreview()};article.append(note);
 if(!c.code){const id=document.createElement('input');id.value=f.code||'';id.placeholder='卡號（可自行補上）';id.setAttribute('aria-label',c.name+' 卡號');id.onchange=()=>{setField(c,'code',id.value.trim());render()};article.append(id)}const actions=textEl('div','actions','');for(const [key,label] of [['have','讓'],['want','求']]){const b=textEl('button',f[key]?key:'',(f[key]?'✓ ':'＋ ')+label);b.setAttribute('aria-pressed',!!f[key]);b.onclick=()=>{setField(c,key,!flags(c)[key]);const active=!!flags(c)[key];b.className=active?key:'';b.textContent=(active?'✓ ':'＋ ')+label;b.setAttribute('aria-pressed',active);refreshSelectionCounts();if($('filter').value!=='all'&&!cardMatchesList(c))renderKeepingPosition();else schedulePreview()};actions.append(b)}article.append(actions);note.hidden=isSale();actions.hidden=isSale();if(isSale())appendSaleControls(article,c);$('cards').append(article)}updateSaleSummary();schedulePreview()}
function loadImage(src){if(!imageCache.has(src)){imageCache.set(src,new Promise((resolve,reject)=>{const img=new Image();const timer=setTimeout(()=>{imageCache.delete(src);reject(Error('卡圖載入逾時，請確認圖庫後重試。'))},15000);img.onload=()=>{clearTimeout(timer);resolve(img)};img.onerror=()=>{clearTimeout(timer);imageCache.delete(src);reject(Error('卡圖無法載入，請連網下載離線圖庫。'))};img.src=src}))}return imageCache.get(src)}
function lines(ctx,text,x,y,maxWidth,lineHeight,maxLines=2){const chars=Array.from(String(text||''));let row='',n=0;for(let i=0;i<chars.length;i++){const ch=chars[i];if(ctx.measureText(row+ch).width>maxWidth&&row){if(n===maxLines-1){ctx.fillText(row.slice(0,-1)+'…',x,y+n*lineHeight);return}ctx.fillText(row,x,y+n*lineHeight);row='';n++}row+=ch}ctx.fillText(row,x,y+n*lineHeight)}
async function makeCanvas(){if(isSale())return makeSaleCanvas();const mode=$('mode').value,cols=+$('columns').value,title=$('title').value,groups=mode==='exchange'?[['have','讓 · 我有的／可讓出'],['want','求 · 想徵求']]:[[mode,mode==='have'?'讓 · 我有的／可讓出':'求 · 想徵求']];const lists=groups.map(([key])=>allCards().filter(c=>flags(c)[key]).map(c=>({...c,displayCode:code(c),note:flags(c).note||''})));const width=1200,gap=24,pad=32,panelW=(width-pad*2-gap*(groups.length-1))/groups.length,cw=(panelW-32-(cols-1)*12)/cols,ch=cw*473/300+115,rows=Math.max(1,...lists.map(l=>Math.ceil(l.length/cols))),height=Math.ceil(170+rows*ch+65);if(height>16000)throw Error('交換表太長，請選每排 5 張或減少選取卡片後再下載。');const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');ctx.fillStyle='#fbf5f9';ctx.fillRect(0,0,width,height);ctx.textAlign='center';ctx.fillStyle='#73518d';ctx.font='bold 34px system-ui';lines(ctx,title,width/2,64,width-100,40,1);let failed=0;
 for(let g=0;g<groups.length;g++){const x=pad+g*(panelW+gap);ctx.fillStyle='white';ctx.fillRect(x,105,panelW,height-155);ctx.fillStyle=groups[g][0]==='have'?'#b44c7a':'#487ab5';ctx.font='bold 23px system-ui';ctx.fillText(groups[g][1],x+panelW/2,146);if(!lists[g].length){ctx.font='20px system-ui';ctx.fillStyle='#a38cae';ctx.fillText('尚未選擇卡片',x+panelW/2,235)}for(let n=0;n<lists[g].length;n++){const c=lists[g][n],cx=x+16+(n%cols)*(cw+12),cy=175+Math.floor(n/cols)*ch,ih=cw*473/300;try{const img=await loadImage(c.front),scale=Math.min(cw/img.width,ih/img.height);ctx.drawImage(img,cx+(cw-img.width*scale)/2,cy+(ih-img.height*scale)/2,img.width*scale,img.height*scale)}catch(e){failed++;ctx.fillStyle='#eee6f2';ctx.fillRect(cx,cy,cw,ih);ctx.fillStyle='#84688e';ctx.font='14px system-ui';ctx.fillText('圖片未下載',cx+cw/2,cy+ih/2)}ctx.fillStyle='#493b52';ctx.font='bold 15px system-ui';lines(ctx,c.displayCode,cx+cw/2,cy+ih+23,cw,18,1);ctx.font='14px system-ui';lines(ctx,c.name,cx+cw/2,cy+ih+45,cw,18,2);ctx.fillStyle='#a25079';lines(ctx,c.note,cx+cw/2,cy+ih+86,cw,17,1)}}ctx.font='14px system-ui';ctx.fillStyle='#a28cae';ctx.fillText('偶像卡片交換工作室 · 非官方工具',width/2,height-20);return {canvas,failed}}
function schedulePreview(){const gen=++previewGeneration;clearTimeout(previewTimer);previewTimer=setTimeout(()=>makeCanvas().then(({canvas})=>{if(gen!==previewGeneration)return;const target=$('preview');target.width=canvas.width;target.height=canvas.height;target.getContext('2d').drawImage(canvas,0,0)}).catch(e=>notify(e.message)),120)}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
$('download').onclick=async()=>{const mode=$('mode').value;if(isSale()){if(!saleCards().length)return notify('請先勾選可賣的卡片。');if(saleCards().some(c=>!validQuantity(saleFlags(c).quantity)||(!blankPrice(saleFlags(c).price)&&!validPrice(saleFlags(c).price))))return notify('請修正數量（1–9999 的整數）與單價（0–999999.99），再匯出。')}else if(!allCards().some(c=>mode==='exchange'?(flags(c).have||flags(c).want):flags(c)[mode]))return notify('請先選取要讓／求的卡片。');const btn=$('download');btn.disabled=true;notify('正在產生表圖…');try{const {canvas,failed}=await makeCanvas();if(failed)throw Error(`${failed} 張圖片未載入，請先下載離線圖庫後重試。`);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));if(!blob)throw Error('圖片產生失敗');download(blob,($('title').value||'交換表').replace(/[\\/:*?"<>|]/g,'_')+'.png');notify('PNG 已產生，請查看下載檔案。')}catch(e){notify('下載失敗：'+e.message)}finally{btn.disabled=false}};
$('backup').onclick=()=>download(new Blob([JSON.stringify({format:'aipri-card-studio',version:2,state},null,2)],{type:'application/json'}),'偶像卡片清單備份.json');
function validImage(s){return typeof s==='string'&&/^data:image\/(png|jpeg|webp);base64,/.test(s)}
$('restore').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{await ready;const data=JSON.parse(await f.text());if(data.format!=='aipri-card-studio'||!data.state||!data.state.items||typeof data.state.items!=='object'||Array.isArray(data.state.items)||!Array.isArray(data.state.custom)||!data.state.custom.every(c=>typeof c.uid==='string'&&typeof c.name==='string'&&validImage(c.front)&&(!c.back||validImage(c.back))))throw Error('備份格式不正確');for(const [uid,value] of Object.entries(data.state.items)){if(!value||typeof value!=='object'||['__proto__','constructor','prototype'].includes(uid))throw Error('清單內容無效')}for(const [uid,value] of Object.entries(data.state.items)){state.items[uid]={have:!!value.have,want:!!value.want,note:String(value.note||''),code:String(value.code||'')}}if(data.state.saleItems){for(const [uid,v] of Object.entries(data.state.saleItems)){if(['__proto__','constructor','prototype'].includes(uid)||!v||typeof v!=='object')throw Error('販售清單內容無效');state.saleItems[uid]={selected:!!v.selected,quantity:String(v.quantity??'1'),price:String(v.price??'')}}}if(typeof data.state.saleTitle==='string')state.saleTitle=data.state.saleTitle;const current=new Map(state.custom.map(c=>[c.uid,c]));data.state.custom.forEach(c=>current.set(c.uid,c));state.custom=[...current.values()];await save();refreshSets();render();notify('備份已合併還原。')}catch(err){notify('還原失敗：'+err.message)}e.target.value=''};
function dataURL(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})}
$('images').onchange=async e=>{await ready;let count=0;const pairs=new Map();for(const file of e.target.files){try{const raw=await dataURL(file),image=await loadImage(raw),canvas=document.createElement('canvas'),scale=Math.min(1,1000/Math.max(image.width,image.height));canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);const name=file.name.replace(/\.[^.]+$/,''),match=name.match(/^(.*?)[_-](front|back)$/i),key=match?match[1]:name,side=match?match[2].toLowerCase():'front';if(!pairs.has(key))pairs.set(key,{uid:crypto.randomUUID(),code:key,name:key,set:0});pairs.get(key)[side]=canvas.toDataURL('image/webp',.9);imageCache.delete(raw)}catch(err){notify('圖片讀取失敗：'+file.name)}}for(const c of pairs.values()){if(!c.front){notify('略過只有背面的卡片：'+c.name);continue}state.custom.push(c);count++}await save();render();notify(`已新增 ${count} 張卡。檔名 _front／_back 可自動配對正反面。`);e.target.value=''};
async function worker(){if(!('serviceWorker' in navigator)||(location.protocol==='file:'||window.IS_STANDALONE))throw Error('此檔案已內建圖庫；要更新請下載最新離線包，或使用 GitHub 網頁版。');await navigator.serviceWorker.register('sw.js');const registration=await navigator.serviceWorker.ready;return registration.active||registration.waiting||registration.installing}
async function cacheLibrary(){const btn=$('offline');btn.disabled=true;try{await worker();const cache=await caches.open('aipri-assets-v1'),urls=[...new Set(catalog.cards.flatMap(c=>[c.front,c.back]).filter(Boolean))];let done=0;for(const url of urls){const request=new Request(new URL(url,location.href));if(!await cache.match(request)){const response=await fetch(request);if(!response.ok)throw Error('下載失敗：'+url);await cache.put(request,response)}done++;if(done%10===0||done===urls.length)notify(`離線圖庫：${done} / ${urls.length} 張圖片`)}notify('離線圖庫下載完成，斷網也能使用。')}catch(e){notify(e.message)}finally{btn.disabled=false}}
if($('offline'))$('offline').onclick=cacheLibrary;
$('update').onclick=async()=>{const btn=$('update');btn.disabled=true;try{if((location.protocol==='file:'||window.IS_STANDALONE))throw Error('單檔離線版請下載最新版本；GitHub 網頁版支援線上更新。');notify('檢查圖庫版本…');const response=await fetch('data/catalog.json',{cache:'no-store'});if(!response.ok)throw Error('圖庫讀取失敗');const next=await response.json();if(next.schemaVersion!==1||!Array.isArray(next.cards))throw Error('不支援的圖庫格式');if(next.version===catalog.version)return notify('圖庫已是最新版本。');const cache=await caches.open('aipri-assets-v1');let done=0;const urls=[...new Set(next.cards.flatMap(c=>[c.front,c.back]).filter(Boolean))];for(const url of urls){const parsed=new URL(url,location.href);if(parsed.origin!==location.origin)throw Error('圖庫包含不支援的外部圖片');if(!await cache.match(parsed.href)){const r=await fetch(parsed.href);if(!r.ok)throw Error('更新圖片下載失敗');await cache.put(parsed.href,r)}if(++done%20===0)notify(`更新圖片 ${done} / ${urls.length}`)}next.savedAt=Date.now();next.baseVersion=bundledVersion;await write('catalog',next);catalog=next;refreshSets();render();notify('圖庫更新完成，你的讓／求和備註已保留。')}catch(e){notify(e.message)}finally{btn.disabled=false}};
for(const id of ['search','set','rarity','filter','character','sort'])$(id).addEventListener('input',()=>{pageSize=40;render()});$('more').onclick=()=>{pageSize+=40;render()};$('mode').addEventListener('change',()=>switchStudio($('mode').value==='sale'?'sale':'exchange',true));for(const id of ['title','columns'])$(id).addEventListener('input',()=>{if(isSale())state.saleTitle=$('title').value;else state.title=$('title').value;save();schedulePreview()});ready.then(()=>{refreshSets();initSaleUI();switchStudio('sale');if(location.protocol!=='file:'&&!window.IS_STANDALONE)worker().catch(()=>{});else if($('offline')){$('offline').disabled=true;$('offline').textContent='圖庫已內建'}}).catch(e=>{notify('無法開啟本機儲存，請改用一般瀏覽模式：'+e.message);refreshSets();render()});
function isSale(){return $('mode').value==='sale'}
function saleFlags(c){return state.saleItems?.[c.uid]||{selected:false,quantity:'1',price:''}}
function saleCards(){return allCards().filter(c=>saleFlags(c).selected)}
function blankPrice(v){return v===undefined||v===null||String(v).trim()===''}
function validQuantity(v){return /^\d+$/.test(String(v))&&Number(v)>=1&&Number(v)<=9999}
function validPrice(v){return !blankPrice(v)&&/^\d+(\.\d{1,2})?$/.test(String(v))&&Number(v)<=999999.99}
function priceLabel(v){return blankPrice(v)?'單價未填':validPrice(v)?'NT$ '+Number(v).toLocaleString('zh-TW',{maximumFractionDigits:2})+'／張':'單價無效'}
function setSale(c,k,v){state.saleItems=state.saleItems||{};state.saleItems[c.uid]={...saleFlags(c),[k]:v};save();updateSaleSummary();schedulePreview()}
function appendSaleControls(article,c){const f=saleFlags(c);article.classList.toggle('sale-selected',!!f.selected);const label=textEl('label','sale-check','');const check=document.createElement('input');check.type='checkbox';check.checked=!!f.selected;check.setAttribute('aria-label',code(c)+' 可賣');check.onchange=()=>{setSale(c,'selected',check.checked);article.classList.toggle('sale-selected',check.checked);if($('filter').value==='sale'&&!check.checked)renderKeepingPosition()};label.append(check,document.createTextNode('可賣 · 加入販售表'));article.append(label);const price=textEl('div','sale-price',priceLabel(f.price));article.append(price);const row=textEl('div','sale-fields','');for(const [key,caption,max] of [['quantity','數量（張）','9999'],['price','單價（NT$／張）','999999.99']]){const l=textEl('label','field',caption),input=document.createElement('input');input.type='number';input.min=key==='quantity'?'1':'0';input.max=max;input.step=key==='quantity'?'1':'0.01';input.inputMode=key==='quantity'?'numeric':'decimal';input.value=f[key]??(key==='quantity'?'1':'');input.placeholder=key==='price'?'未填':'';input.setAttribute('aria-label',code(c)+' '+caption);input.oninput=()=>{setSale(c,key,input.value);const ok=key==='quantity'?validQuantity(input.value):(blankPrice(input.value)||validPrice(input.value));input.setAttribute('aria-invalid',!ok);input.setCustomValidity(ok?'':key==='quantity'?'請填 1–9999 的整數':'請填 0–999999.99，最多兩位小數');if(key==='price')price.textContent=priceLabel(input.value)};l.append(input);row.append(l)}article.append(row)}
function sortCards(cards){const sort=$('sort').value;if(sort==='code')cards.sort((a,b)=>code(a).localeCompare(code(b),'zh-TW',{numeric:true}));if(sort.startsWith('price-'))cards.sort((a,b)=>{const x=saleFlags(a).price,y=saleFlags(b).price;if(!validPrice(x))return validPrice(y)?1:0;if(!validPrice(y))return -1;return (Number(x)-Number(y))*(sort==='price-desc'?-1:1)})}
function updateSaleSummary(){if(!$('sale-summary'))return;const cards=saleCards(),missing=cards.filter(c=>blankPrice(saleFlags(c).price)).length;$('sale-summary').hidden=!isSale();$('sale-summary').textContent=`已勾選 ${cards.length} 種卡片${missing?' · '+missing+' 種單價未填':''} · 僅匯出勾選卡片`}
function switchStudio(kind,keepMode=false){const sale=kind==='sale';if(!keepMode)$('mode').value=sale?'sale':'exchange';$('sale-tab').setAttribute('aria-pressed',sale);$('exchange-tab').setAttribute('aria-pressed',!sale);document.body.classList.toggle('sale-mode',sale);$('title').value=sale?(state.saleTitle||'我的卡片販售表'):(state.title||'我的卡片交換表');document.querySelector('.library .hint').textContent=sale?'點卡圖看背面 · 勾選「可賣」，填數量與每張單價':'點卡圖看背面 · 點「讓／求」加入清單';$('preview').setAttribute('aria-label',sale?'販售表預覽':'交換表預覽');$('workbench-label').textContent=sale?'販售表工作台':'交換表工作台';$('view-sheet').textContent=sale?'查看販售表 ↓':'查看交換表 ↓';document.querySelector('header p').textContent=sale?'勾選可賣卡片、填數量與單價，做成社團販售表。':'翻看卡片正反面，整理「讓」與「求」，做成交換表。';$('maker-hint').textContent=sale?'販售表只匯出已勾選卡片，金額為每張單價（NT$）。未填單價會標示「單價未填」。清單只保存在此瀏覽器。':'備註會出現在交換圖中。讓／求清單與備註只保存在此瀏覽器，不會上傳。';$('filter').value='all';render()}
function initSaleUI(){$('view-sheet').onclick=()=>{$('workbench').scrollIntoView({block:'start',behavior:'smooth'})};$('sale-tab').onclick=()=>switchStudio('sale');$('exchange-tab').onclick=()=>switchStudio('exchange');[...new Set(allCards().map(c=>c.character).filter(Boolean))].sort().forEach(c=>$('character').add(new Option(c,c)));const container=$('category-buttons');for(const [value,label] of [['','全部卡片'],['1','第 1 彈'],['2','第 2 彈'],['3','第 3 彈'],['4','第 4 彈'],['5','第 5 彈'],['6','第 6 彈'],['event','活動／商品卡']]){const b=textEl('button','category-button',label);b.onclick=()=>{$('set').value=value;pageSize=40;render()};container.append(b)}}
function wrappedText(ctx,text,width){let rows=[],row='';for(const ch of String(text||'')){if(ctx.measureText(row+ch).width>width&&row){rows.push(row);row=''}row+=ch}rows.push(row);return rows}
async function makeSaleCanvas(){const cards=saleCards(),cols=+$('columns').value,width=1200,pad=40,gap=24,cw=(width-pad*2-gap*(cols-1))/cols,ih=cw*473/300,ctxMeasure=document.createElement('canvas').getContext('2d');ctxMeasure.font='18px system-ui';const entries=cards.map(c=>({c,codeRows:(ctxMeasure.font='bold 18px system-ui',wrappedText(ctxMeasure,code(c),cw)),nameRows:(ctxMeasure.font='18px system-ui',wrappedText(ctxMeasure,c.name,cw))}));const rowHeights=[];for(let i=0;i<entries.length;i+=cols)rowHeights.push(ih+Math.max(...entries.slice(i,i+cols).map(e=>(e.codeRows.length+e.nameRows.length)*24))+100);const height=Math.ceil(180+rowHeights.reduce((a,b)=>a+b,0));if(height>16000)throw Error('販售表過長，請選一排 5 張或分批勾選後匯出（最多 16000 像素）。');const canvas=document.createElement('canvas');canvas.width=width;canvas.height=Math.max(400,height);const ctx=canvas.getContext('2d');ctx.fillStyle='#faf7fb';ctx.fillRect(0,0,width,canvas.height);ctx.textAlign='center';ctx.fillStyle='#73518d';ctx.font='bold 34px system-ui';let title=$('title').value||'我的卡片販售表';while(ctx.measureText(title).width>width-80&&parseInt(ctx.font.match(/\d+/)[0])>12)ctx.font=`bold ${parseInt(ctx.font.match(/\d+/)[0])-1}px system-ui`;ctx.fillText(title,width/2,60);ctx.font='18px system-ui';ctx.fillStyle='#806b8a';ctx.fillText(`可賣 ${cards.length} 種 · 金額為每張單價（NT$）`,width/2,100);let failed=0,cy=130;for(let i=0;i<entries.length;i+=cols){for(let j=0;j<cols&&i+j<entries.length;j++){const {c,codeRows,nameRows}=entries[i+j],x=pad+j*(cw+gap),f=saleFlags(c);try{const image=await loadImage(c.front),scale=Math.min(cw/image.width,ih/image.height);ctx.drawImage(image,x+(cw-image.width*scale)/2,cy+(ih-image.height*scale)/2,image.width*scale,image.height*scale)}catch(e){failed++;ctx.fillStyle='#eee';ctx.fillRect(x,cy,cw,ih)}let y=cy+ih+25;ctx.fillStyle='#493b52';ctx.font='bold 18px system-ui';for(const row of codeRows){ctx.fillText(row,x+cw/2,y);y+=24}ctx.font='18px system-ui';for(const row of nameRows){ctx.fillText(row,x+cw/2,y);y+=24}ctx.fillStyle='#73518d';ctx.font='bold 20px system-ui';ctx.fillText(validQuantity(f.quantity)?`數量 ${Number(f.quantity)} 張`:'數量無效',x+cw/2,y+5);ctx.fillStyle='#b44c7a';ctx.font='bold 20px system-ui';let amount=priceLabel(f.price);while(ctx.measureText(amount).width>cw&&parseInt(ctx.font.match(/\d+/)[0])>12)ctx.font=`bold ${parseInt(ctx.font.match(/\d+/)[0])-1}px system-ui`;ctx.fillText(amount,x+cw/2,y+35)}cy+=rowHeights[i/cols]}if(!cards.length){ctx.fillStyle='#806b8a';ctx.font='24px system-ui';ctx.fillText('尚未勾選可賣卡片',width/2,235)}ctx.fillStyle='#a28cae';ctx.font='14px system-ui';ctx.fillText('偶像卡片交換工作室 · 非官方工具',width/2,canvas.height-18);return {canvas,failed}}

function refreshSelectionCounts(){const cards=allCards();$('counts').textContent=`讓 ${cards.filter(c=>flags(c).have).length} 張　／　求 ${cards.filter(c=>flags(c).want).length} 張`;updateSaleSummary()}
function cardMatchesList(c){const filter=$('filter').value,f=flags(c);return filter==='all'||(filter==='sale'?saleFlags(c).selected:filter==='selected'?(f.have||f.want):f[filter])}
function renderKeepingPosition(){const x=window.scrollX,y=window.scrollY,active=document.activeElement,aria=active?.getAttribute('aria-label');render();if(aria){const same=[...document.querySelectorAll('[aria-label]')].find(el=>el.getAttribute('aria-label')===aria);same?.focus({preventScroll:true})}window.scrollTo(x,y);requestAnimationFrame(()=>window.scrollTo(x,y))}
